### ISSUE TITLE
Exception thrown while using webhookurl while it is working fine when token is passed

### ISSUE THREAD

**Issue by jivanpuri** [maricn/logback-slack-appender#7]
```
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@8:15 - no applicable action for [webhookUri], current ElementPath  is [[configuration][appender][webhookUri]]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:195)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:65)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:289)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:262)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:231)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:207)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at employee.EmployeeBoot.main(EmployeeBoot.java:26)
```

**Comment by maricn** [comment]
@jivanpuri Could you also attach your configuration XML?

**Comment by jivanpuri** [comment]
# File configuration:

```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
	<appender name="SLACK" class="com.github.maricn.logback.SlackAppender">
		<webhookUri>---MASKED---</webhookUri>
		<channel>#general</channel>
		<layout class="ch.qos.logback.classic.PatternLayout">
			 <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{0} %X{akkaSource} -%msg%n</pattern>
		</layout>
		<username>${HOSTNAME}</username>
		<iconEmoji>:stuck_out_tongue_winking_eye:</iconEmoji>
	</appender>

	<!-- Currently recommended way of using Slack appender -->
	<appender name="ASYNC_SLACK" class="ch.qos.logback.classic.AsyncAppender">
		<appender-ref ref="SLACK" />
	</appender>

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{0} %X{akkaSource} -%msg%n</pattern>
        </encoder>
    </appender>
    <root level="info">
        <appender-ref ref="ASYNC_SLACK" />
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

**Comment by maricn** [comment]
Hi @jivanpuri,

I have fixed formatting issue with your message. Also, I have removed your `webhookUrl`. You should probably renew it, since you might not want to share it publicly.

Could you try using latest version of `logback-slack-adapter` (1.3.0) and report if you still experience the issue? Thanks.

**Comment by jivanpuri** [comment]
Yes, it is working; I have tested with new version logback-slack-adapter (1.3.0)
Thanks a ton!!
